
# Project identifier used for namespacing functions and tags. Should align with the namespace in the source folder.
id: "furnace_nbt_recipes"
# Project name that will be used in messages, item lore, etc.
name: "FurnaceNbtRecipes"
# Author(s) name(s) displayed in pack.mcmeta, also used to add 'convention.debug' tag to the players of the same name(s) <-- showing additionnal displays like datapack loading
author: "Stoupy51"
# Project version in semantic versioning format: major.minor.patch (e.g., 1.0.0 or 2.84.615).
version: "1.10.0"
# Minecraft version. Determines what resources beet loads (plugins like `mecha` determine what commands to use). Defaults: Latest
minecraft: "1.21.8"

# Defines the directory that beet uses for the base path
directory: "."
# Path to a folder for beet to output. If not defined, no files will visibly output
output: "build"

# Takes a nested pack config, see PackConfig() documentation
data_pack:
    name: "datapack"

# A list of strings or dicts representing "plugins".
pipeline:
    - "stewbeet.plugins.initialize"
    - "stewbeet.plugins.datapack.loading"
    - "user.link"
    - "stewbeet.plugins.finalyze.basic_datapack_structure"
    - "stewbeet.plugins.finalyze.dependencies"
    - "stewbeet.plugins.finalyze.last_final"
    - "stewbeet.plugins.auto.headers"
    - "stewbeet.plugins.archive"
    - "stewbeet.plugins.copy_to_destination"
    - "stewbeet.plugins.compute_sha1"

# Generic dict which holds extra information usable by plugins
meta:
    # List of supported Minecraft versions (used when uploading to Modrinth or Smithed)
    mc_supports: ["1.21.8", "1.21.9", "1.21.10", "1.21.11", "infinite"]

